# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e781e9e1cf034cac06797152ecd9e2e4d3da2f5b2c1a15ffc6336860fecca59f1dfe4ca661a5a1ba47ca961ede833a3f3366a453494250b8aff78b62be496c90

test:
  secret_key_base: 5f11607bc8b31afbcda162d8b91b554050541f8aef6261fa75ef7e9ea9f50f575f5ac6457ea4dabbc1cea4726c73627787dcd85993ec146fa6bbc0c3149a953e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
